version: '3.8'
services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_USER=monuser
      - DB_PASSWORD=monpassword
      - DB_NAME=madatabase
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=monuser
      - POSTGRES_PASSWORD=monpassword
      - POSTGRES_DB=madatabase

volumes:
  postgres_data:
