version: '3.8'
services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_USER=oj_user
      - DB_PASSWORD=p49cykAhdqQJSxzm2K358t
      - DB_NAME=open_journal
    depends_on:
      - db

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "80:80"
    depends_on:
      - backend

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=oj_user
      - POSTGRES_PASSWORD=p49cykAhdqQJSxzm2K358t
      - POSTGRES_DB=open_journal

volumes:
  postgres_data:
